//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchiveTakeMedicine
    {
        public long Id { get; set; }
        public long userId { get; set; }
        public long medicineToChild { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime time { get; set; }
    }
}
