//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MediDBEntitie : DbContext
    {
        public MediDBEntitie()
            : base("name=MediDBEntitie")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArchiveTakeMedicine> ArchiveTakeMedicines { get; set; }
        public virtual DbSet<Guardian> Guardians { get; set; }
        public virtual DbSet<guardiansToUser> guardiansToUsers { get; set; }
        public virtual DbSet<HMO> HMOes { get; set; }
        public virtual DbSet<KingOfDosage> KingOfDosages { get; set; }
        public virtual DbSet<Medicine> Medicines { get; set; }
        public virtual DbSet<MedicinesToChild> MedicinesToChilds { get; set; }
        public virtual DbSet<TimeOfDay> TimeOfDays { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
