//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class guardiansToUser
    {
        public int Id { get; set; }
        public long userId { get; set; }
        public long guardianId { get; set; }
    
        public virtual Guardian Guardian { get; set; }
        public virtual User User { get; set; }
    }
}
