//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.guardiansToUsers = new HashSet<guardiansToUser>();
            this.MedicinesToChilds = new HashSet<MedicinesToChild>();
        }
    
        public long Id { get; set; }
        public string usreId { get; set; }
        public string userName { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public int userHMO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<guardiansToUser> guardiansToUsers { get; set; }
        public virtual HMO HMO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicinesToChild> MedicinesToChilds { get; set; }
    }
}
